<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE matricula SYSTEM "Ejercicio14Externo.dtd">
<!DOCTYPE matricula [
<!ELEMENT matricula (personal,pago)>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT personal (dni,nombre,titulacion,curso_academico,domicilios+)>
<!ELEMENT personal EMPTY>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT titulacion (#PCDATA)>
<!ELEMENT curso_academico (#PCDATA)>
<!ELEMENT domicilios (nombre)>
<!ELEMENT domicilios (#PCDATA)>
<!ATTLIST domicilio tipo familiar|habitual #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT pago (tipo_matricula)>
<!ELEMENT pago EMPTY>
<!ELEMENT tipo_matricula (#PCDATA)>
]>
<matricula>
    <personal>
        <dni>99223366M</dni>
        <nombre>Juan Pardo Martín</nombre>
        <titulacion>Ingeniería Informática</titulacion>
        <curso_academico>1997/1998</curso_academico>
        <domicilios>
            <domicilio tipo="familiar">
                <nombre>C/ Principal nº1</nombre>
            </domicilio>
            <domicilio tipo="habitual">
                <nombre>C/ Secundaria nº2</nombre>
            </domicilio>
            </domicilios>
    </personal>
    <pago>
        <tipo_matricula>Matrícula Ordinaria</tipo_matricula>
    </pago>
</matricula>