<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE receta [
<!ELEMENT receta (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT ingredientes (#PCDATA)>
<!ELEMENT procedimiento (#PCDATA)>
]>
<receta>
<parrafo>Esto es un p√°rrafo</parrafo>
<titulo>...</titulo>
<ingredientes>...</ingredientes>
<procedimiento>...</procedimiento>
</receta>

